### ISSUE TITLE
Issue with screenshot format

### ISSUE THREAD

**Issue by hamzaabamboo** [sigonasr2/d4djRankReader#1]
Hi sig, I planned to continue running the OCR code.
I tried to run the code on my own and I got it up and running. I think i'm pretty close to having it working. but what's missing is that the screenshot seems to be wrong.

Would you mind telling how you make those screen captures ?

**Comment by sigonasr2** [comment]
The application I built at https://github.com/sigonasr2/d4djRankReader requires three things to make working at this time:
 - It needs a google vision API token. You can get one from google developers, there is a 3-month trial that can be cycled through constantly and renewed with a valid billing account by cycling google accounts. This is for the OCR itself. I attach a sample of what the key file is supposed to look like. Per the Google Vision implementation docs, you will create a system environment variable called GOOGLE_APPLICATION_CREDENTIALS and make its value equal to the exact location of this token file.
- It needs a blank Screenshots directory located in the same location as the jar file itself. Note that the app will delete any files that already exist in this folder when it starts up.
- When 5 screenshots are taken and inserted into the Screenshots directory, the app will do its cropping algorithm to create an image called testing_leaderboardnames.png. It then sends this image file through Google Vision API and returns the OCR values which are then uploaded to the server.

The source code must be modified for each event as the EVENTID is hardcoded here: https://github.com/sigonasr2/d4djRankReader/blob/master/src/main/java/d4dj/d4dj/App.java#L115

Each screenshot is assumed to be exactly 900x900 pixels resolution, based on an emulator screenshot.
The screenshots must contain these things and inserted into the folder in this order:
Screenshot 1: The top 7 positions of the leaderboard (no scrolling).
Screenshot 2: Positions 8-13 on the leaderboard.
Screenshot 3: Positions 14-20 on the leaderboard (scrolled all the way to the bottom).
Screenshot 4: Positions 50-10000 (no scrolling)
Screenshot 5: Positions 20000-50000 (scrolled all the way to the bottom)

____________________

For future reference.
